// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web platformu desteklenmiyor.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'Bu platform için Firebase yapılandırması yok.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXrtG-S9kCIxJ0j20i8gFQjzTi1kZLleM',
    appId: '1:663004532552:ios:fa64a7331382587c45ad7d',
    messagingSenderId: '663004532552',
    projectId: 'ai-study-assistant-dev-30a40',
    storageBucket: 'ai-study-assistant-dev-30a40.firebasestorage.app',
    iosClientId:
        '663004532552-h40msg8925sn75hlb5b67lhisbthogrr.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentHelpDesk',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLVK3SxFF5O09lja3pN7KTnPw5XfyIXCI',
    appId: '1:663004532552:android:8881c0f26bf47de845ad7d',
    messagingSenderId: '663004532552',
    projectId: 'ai-study-assistant-dev-30a40',
    storageBucket: 'ai-study-assistant-dev-30a40.firebasestorage.app',
  );
}
